version: "2.28"
services:
  app:
    container_name: habr_parser
    build: .
    volumes:
      - /app:/app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: resumes_db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Папка для скриптов инициализации
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: resumes_db
      POSTGRES_PASSWORD: postgres
    command: []
    ports:
      - 5432:5432
